name: 'Hello World'
description: 'Greet Someone'
inputs:
  MY_NAME:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random Number"
    value: ${{ steps.random-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.MY_NAME }}.
      shell: bash
